### ISSUE TITLE
Can't run the bot.js

### ISSUE THREAD

**Issue by ryanNewcodeer123** [WebDevSimplified/wds-discord-bot#3]
Hi, I just copied the code and typed npm start on the terminal, and this happens:

![bot js](https://user-images.githubusercontent.com/110335999/191348068-ee93719e-aedb-455e-9191-f90ca0d978b0.png)
I am using vscode and also installed the discord.js

How to fix that?

**Comment by WebDevSimplified** [comment]
This is not a bot that is meant to be used by others. This is the code for the bot I use on my Discord Server.
